### ISSUE TITLE
Unable to get information printed from F11

### ISSUE THREAD

**Issue by Shaksos** [linus-jansson/btd6farmer#10]
Pretty new to all of this but I think it needs a .json file. if a string file is needed, the log.py has an error where it looks for a ".join" file. idk if this is right or not, but I think it's supposed to be .json?

**Comment by linus-jansson** [comment]
Not really sure what the problem that you are experiencing is, is it `log_stats()` that you are having issues with?

You got any error that you can send?

**Comment by Shaksos** [comment]
no errors, just nothing shows up in the game or in the terminal (PS)

**Comment by linus-jansson** [comment]
Ah, my bad I had that feature implemented before but it went a couple commits ago since I thought it got too bloated and clunky. Forgot to remove it from the readme.

If you want to run the script with some sort of stats output you could add `--debug` as a run option when running the bot, it will generate a json file after every match that will show some info on how many matches the bot has won, lost and the average matchtime.
