### ISSUE TITLE
The Y-coordinate is increasing by 1 on multiple occasions for the permaspike tower in instructions.csv

### ISSUE THREAD

**Issue by Shaksos** [linus-jansson/btd6farmer#8]
It starts off at 384, but increases by 1, 4 additional times. This might move the cursor just far enough away from the tower, that it will not be selected.

Also an insignificant thing, some of the info text is still in Swedish

**Comment by linus-jansson** [comment]
Should be fixed in [bdf7651](https://github.com/linus-jansson/btd6farmer/commit/bdf7651fc797ba60d53d727aeb06b888f95dbab9) and [d06f45e](https://github.com/linus-jansson/btd6farmer/commit/d06f45e69087364ce93ae1b55f5c8d2c8fe408cf). The positions must have been incrementing when I created the instructions somehow 

Excuse me for the lazy commenting in swedish,://

Cheers!
